// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFoVcHXvQOGy2T-hUHCoJx7grPr_FFK58',
    appId: '1:746880067935:web:8953946fc3b7d183166eea',
    messagingSenderId: '746880067935',
    projectId: 'flash-chat-75659',
    authDomain: 'flash-chat-75659.firebaseapp.com',
    storageBucket: 'flash-chat-75659.appspot.com',
    measurementId: 'G-FV3X1H6P5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGlAjPIi-dAwy0l_O4RSHLv_6PalqGxiI',
    appId: '1:746880067935:android:140a061f5b27cff9166eea',
    messagingSenderId: '746880067935',
    projectId: 'flash-chat-75659',
    storageBucket: 'flash-chat-75659.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0LQHS7Yi8YjTrcQ9n_Ujv5w-zl-mTvM',
    appId: '1:746880067935:ios:41ddcdd5c210c271166eea',
    messagingSenderId: '746880067935',
    projectId: 'flash-chat-75659',
    storageBucket: 'flash-chat-75659.appspot.com',
    iosClientId: '746880067935-3jtj5dk3sb57epm1hmm83c41aeh1ekpa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
